/* FOR EARLY ADOPTERS */

GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.SI_VERSION to BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.FG_DELIVERY to BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.FG_ROUTE to BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.FG_ARRIVEDFILE to BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.MBX_MESSAGE to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_ASYNC_CD to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_DEFER_DELIVERY to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_DOC_STORAGE to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_FILE to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_FCM_MSGID_TRACKER to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_FLOW_CONTROL to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_INTERFACE to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_SWR_FILESTATUS to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_TRACKING to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_MQ_TRANSFER to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_SFGLEGACY_LINK to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_WF_THREAD to BFGBP_APPUSER_ROLE;

GRANT EXECUTE ON RBS_BFG_CUSTOM_OWNER.GET_ASYNC_CD_FILELIST to BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_BUNDLE_IDSEQ TO BFGBP_APPUSER_ROLE;


CREATE USER BFGBP_APPUSER IDENTIFIED BY {PASSWORD}
Profile EF_ORACLE_BATCH_NOEXPIRE
Default tablespace users temporary tablespace user_temp;

GRANT CREATE SESSION TO BFGBP_APPUSER_ROLE;

GRANT BFGBP_APPUSER_ROLE TO BFGBP_APPUSER;

GRANT CREATE SYNONYM TO BFGBP_APPUSER_ROLE;

Alter session set current_Schema=BFGBP_APPUSER;

SET ROLE BFGBP_APPUSER_ROLE;

create or replace synonym "FB_ASYNC_CD" for "RBS_BFG_CUSTOM_OWNER"."FB_ASYNC_CD";
create or replace synonym "FB_FILE" for "RBS_BFG_CUSTOM_OWNER"."FB_FILE";
create or replace synonym "FB_DOC_STORAGE" for "RBS_BFG_CUSTOM_OWNER"."FB_DOC_STORAGE";
create or replace synonym "FB_DEFER_DELIVERY" for "RBS_BFG_CUSTOM_OWNER"."FB_DEFER_DELIVERY";
create or replace synonym "FB_GR_FCM_MSGID_TRACKER" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_FCM_MSGID_TRACKER";
create or replace synonym "FB_GR_FLOW_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_FLOW_CONTROL";
create or replace synonym "FB_GR_INTERFACE" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_INTERFACE";
create or replace synonym "FB_GR_SWR_FILESTATUS" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_SWR_FILESTATUS";
create or replace synonym "FB_GR_TRACKING" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_TRACKING";
create or replace synonym "FB_MQ_TRANSFER" for "RBS_BFG_CUSTOM_OWNER"."FB_MQ_TRANSFER";
create or replace synonym "FB_SFGLEGACY_LINK" for "RBS_BFG_CUSTOM_OWNER"."FB_SFGLEGACY_LINK";
create or replace synonym "FB_WF_THREAD" for "RBS_BFG_CUSTOM_OWNER"."FB_WF_THREAD";
create or replace synonym "SCT_ENTITY" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY";
create or replace synonym "SI_VERSION" for "SI_OWNER"."SI_VERSION";
create or replace synonym "FG_DELIVERY" for "SI_OWNER"."FG_DELIVERY";
create or replace synonym "FG_ROUTE" for "SI_OWNER"."FG_ROUTE";
create or replace synonym "FG_ARRIVEDFILE" for "SI_OWNER"."FG_ARRIVEDFILE";
create or replace synonym "MBX_MESSAGE" for "SI_OWNER"."MBX_MESSAGE";

create or replace synonym "GET_ASYNC_CD_FILELIST" for "RBS_BFG_CUSTOM_OWNER"."GET_ASYNC_CD_FILELIST";

Alter session set current_Schema=RBS_BFG_CUSTOM_OWNER;
create or replace public synonym "FB_FILE" for "RBS_BFG_CUSTOM_OWNER"."FB_FILE";
create or replace public synonym "FB_DOC_STORAGE" for "RBS_BFG_CUSTOM_OWNER"."FB_DOC_STORAGE";
GRANT SELECT,UPDATE ON "RBS_BFG_CUSTOM_OWNER"."FB_FILE" to SI_OWNER;
GRANT SELECT ON "RBS_BFG_CUSTOM_OWNER"."FB_DOC_STORAGE" to SI_OWNER;


