/* SEPA */
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE_LOG TO BFGBP_APPUSER_ROLE;
GRANT SELECT, UPDATE ON RBS_BFG_CUSTOM_OWNER.SCT_SCHEDULE TO BFGBP_APPUSER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT TO BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT_ARCHIVE TO BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_BUNDLE TO BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL to BFGBP_APPUSER_ROLE;

create or replace synonym "FB_CHANGE_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."FB_CHANGE_CONTROL";
create or replace synonym "SCT_ENTITY" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY";
create or replace synonym "SCT_TRUSTED_CERTIFICATE" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE";
create or replace synonym "SCT_TRUSTED_CERTIFICATE_LOG" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE_LOG";
create or replace synonym "SCT_SCHEDULE" for "RBS_BFG_CUSTOM_OWNER"."SCT_SCHEDULE";
create or replace synonym "SCT_PAYMENT" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT";
create or replace synonym "SCT_PAYMENT_ARCHIVE" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT_ARCHIVE";
create or replace synonym "SCT_BUNDLE" for "RBS_BFG_CUSTOM_OWNER"."SCT_BUNDLE";
create or replace synonym "SCT_BUNDLE_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_BUNDLE_IDSEQ";
