--sqlplus / as sysdba


--REPLACE {CONTAINER} as required
--Dev=DOGB1575
--NFT=NOGBEF11;

--REPLACE {BFGUI_PASSWORD} as required
--DEV=Bfgapp_12345_dev
--NFT=Bfgapp_12345_nft

--REPLACE {BFGREST_PASSWORD} as required
--DEV=Bfgrest_12345_dev
--NFT=Bfgrest_12345_nft


/*
BFGUI_APPUSER
*/

alter session set container={CONTAINER};

CREATE ROLE BFGUI_APPUSER_ROLE NOT IDENTIFIED;

GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY_LOG TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_SCHEDULE TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE_LOG TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SFG_CHANGE_CONTROL TO BFGUI_APPUSER_ROLE;

CREATE USER BFGUI_APPUSER IDENTIFIED BY {BFGUI_PASSWORD}
Profile EF_ORACLE_BATCH_NOEXPIRE
Default tablespace users temporary tablespace user_temp;

GRANT CREATE SESSION TO BFGUI_APPUSER_ROLE;

GRANT BFGUI_APPUSER_ROLE TO BFGUI_APPUSER;

GRANT CREATE SYNONYM TO BFGUI_APPUSER_ROLE;

Alter session set current_Schema=BFGUI_APPUSER;

SET ROLE BFGUI_APPUSER_ROLE;
create synonym "FB_CHANGE_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."FB_CHANGE_CONTROL";
create synonym "SCT_ENTITY" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY";
create synonym "SCT_ENTITY_LOG" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY_LOG";
create synonym "SCT_SCHEDULE" for "RBS_BFG_CUSTOM_OWNER"."SCT_SCHEDULE";
create synonym "SCT_TRUSTED_CERTIFICATE" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE";
create synonym "SCT_TRUSTED_CERTIFICATE_LOG" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE_LOG";
create synonym "SFG_CHANGE_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."SFG_CHANGE_CONTROL";

GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY_LOG_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_SCHEDULE_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERT_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERT_LOG_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SFG_CHANGE_CONTROL_IDSEQ TO BFGUI_APPUSER_ROLE;

create synonym "FB_CHANGE_CONTROL_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."FB_CHANGE_CONTROL_IDSEQ";
create synonym "SCT_ENTITY_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY_IDSEQ";
create synonym "SCT_ENTITY_LOG_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY_LOG_IDSEQ";
create synonym "SCT_SCHEDULE_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_SCHEDULE_IDSEQ";
create synonym "SCT_TRUSTED_CERT_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERT_IDSEQ";
create synonym "SCT_TRUSTED_CERT_LOG_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERT_LOG_IDSEQ";
create synonym "SFG_CHANGE_CONTROL_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SFG_CHANGE_CONTROL_IDSEQ";

/*
BFGREST_APPUSER
*/

connect / as sysdba
alter session set container={CONTAINER};

CREATE ROLE BFGREST_APPUSER_ROLE NOT IDENTIFIED;

GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT TO BFGREST_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT_ARCHIVE TO BFGREST_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_BUNDLE TO BFGREST_APPUSER_ROLE;
GRANT SELECT, INSERT ON RBS_BFG_CUSTOM_OWNER.SCT_AUDIT TO BFGREST_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY to BFGREST_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_AUDIT_ID_SEQ TO BFGREST_APPUSER_ROLE;

GRANT SELECT ON SI_OWNER.SI_VERSION to BFGREST_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.WORKFLOW_CONTEXT to BFGREST_APPUSER_ROLE;

CREATE USER BFGREST_APPUSER IDENTIFIED BY {BFGREST_PASSWORD}
Profile EF_ORACLE_BATCH_NOEXPIRE
Default tablespace users temporary tablespace user_temp;

GRANT CREATE SESSION TO BFGREST_APPUSER_ROLE;

GRANT BFGREST_APPUSER_ROLE TO BFGREST_APPUSER;

GRANT CREATE SYNONYM TO BFGREST_APPUSER_ROLE;

Alter session set current_Schema=BFGREST_APPUSER;

SET ROLE BFGREST_APPUSER_ROLE;

create or replace synonym "SCT_AUDIT" for "RBS_BFG_CUSTOM_OWNER"."SCT_AUDIT";
create or replace synonym "SCT_BUNDLE" for "RBS_BFG_CUSTOM_OWNER"."SCT_BUNDLE";
create or replace synonym "SCT_PAYMENT" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT";
create or replace synonym "SCT_PAYMENT_ARCHIVE" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT_ARCHIVE";
create or replace synonym "SCT_ENTITY" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY";
create or replace synonym "SCT_AUDIT_ID_SEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_AUDIT_ID_SEQ";
create or replace synonym "SI_VERSION" for "SI_OWNER"."SI_VERSION";
create or replace synonym "WORKFLOW_CONTEXT" for "SI_OWNER"."WORKFLOW_CONTEXT";

Alter session set current_Schema=RBS_BFG_CUSTOM_OWNER;
GRANT SELECT ON "RBS_BFG_CUSTOM_OWNER"."SCT_AUDIT" to SI_OWNER;
Alter session set current_Schema=SI_OWNER;
create or replace synonym "SCT_AUDIT" for "RBS_BFG_CUSTOM_OWNER"."SCT_AUDIT";


/*
BFGBP_APPUSER
*/

connect / as sysdba
alter session set container={CONTAINER};

GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE_LOG TO BFGBP_APPUSER_ROLE;
GRANT SELECT, UPDATE ON RBS_BFG_CUSTOM_OWNER.SCT_SCHEDULE TO BFGBP_APPUSER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT TO BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT_ARCHIVE TO BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_BUNDLE TO BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL to BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_BUNDLE_IDSEQ TO BFGBP_APPUSER_ROLE;
--request from App Support Team
GRANT SELECT, INSERT, UPDATE ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY_IDSEQ TO BFGBP_APPUSER_ROLE;

Alter session set current_Schema=BFGBP_APPUSER;

SET ROLE BFGBP_APPUSER_ROLE;

create or replace synonym "FB_CHANGE_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."FB_CHANGE_CONTROL";
create or replace synonym "SCT_TRUSTED_CERTIFICATE" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE";
create or replace synonym "SCT_TRUSTED_CERTIFICATE_LOG" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE_LOG";
create or replace synonym "SCT_SCHEDULE" for "RBS_BFG_CUSTOM_OWNER"."SCT_SCHEDULE";
create or replace synonym "SCT_PAYMENT" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT";
create or replace synonym "SCT_PAYMENT_ARCHIVE" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT_ARCHIVE";
create or replace synonym "SCT_BUNDLE" for "RBS_BFG_CUSTOM_OWNER"."SCT_BUNDLE";
create or replace synonym "SCT_BUNDLE_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_BUNDLE_IDSEQ";
--request from App Support Team
create or replace synonym "SCT_ENTITY_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY_IDSEQ";

