--sqlplus / as sysdba

alter session set container=DOGB1575;
CREATE ROLE BFGUI_APPUSER_ROLE NOT IDENTIFIED;

GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY_LOG TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_SCHEDULE TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE_LOG TO BFGUI_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SFG_CHANGE_CONTROL TO BFGUI_APPUSER_ROLE;

CREATE USER BFGUI_APPUSER IDENTIFIED BY Bfgapp_12345_dev
Profile EF_ORACLE_BATCH_NOEXPIRE
Default tablespace users temporary tablespace user_temp;

GRANT CREATE SESSION TO BFGUI_APPUSER_ROLE;

GRANT BFGUI_APPUSER_ROLE TO BFGUI_APPUSER;

GRANT CREATE SYNONYM TO BFGUI_APPUSER_ROLE;

Alter session set current_Schema=BFGUI_APPUSER;

SET ROLE BFGUI_APPUSER_ROLE;
create synonym "FB_CHANGE_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."FB_CHANGE_CONTROL";
create synonym "SCT_ENTITY" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY";
create synonym "SCT_ENTITY_LOG" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY_LOG";
create synonym "SCT_SCHEDULE" for "RBS_BFG_CUSTOM_OWNER"."SCT_SCHEDULE";
create synonym "SCT_TRUSTED_CERTIFICATE" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE";
create synonym "SCT_TRUSTED_CERTIFICATE_LOG" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE_LOG";
create synonym "SFG_CHANGE_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."SFG_CHANGE_CONTROL";


GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY_LOG_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_SCHEDULE_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERT_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERT_LOG_IDSEQ TO BFGUI_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SFG_CHANGE_CONTROL_IDSEQ TO BFGUI_APPUSER_ROLE;

create synonym "FB_CHANGE_CONTROL_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."FB_CHANGE_CONTROL_IDSEQ";
create synonym "SCT_ENTITY_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY_IDSEQ";
create synonym "SCT_ENTITY_LOG_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY_LOG_IDSEQ";
create synonym "SCT_SCHEDULE_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_SCHEDULE_IDSEQ";
create synonym "SCT_TRUSTED_CERT_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERT_IDSEQ";
create synonym "SCT_TRUSTED_CERT_LOG_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERT_LOG_IDSEQ";
create synonym "SFG_CHANGE_CONTROL_IDSEQ" for "RBS_BFG_CUSTOM_OWNER"."SFG_CHANGE_CONTROL_IDSEQ";

connect / as sysdba
alter session set container=DOGB1575;

CREATE ROLE BFGREST_APPUSER_ROLE NOT IDENTIFIED;

GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT TO BFGREST_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT_ARCHIVE TO BFGREST_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_BUNDLE TO BFGREST_APPUSER_ROLE;
GRANT SELECT, INSERT ON RBS_BFG_CUSTOM_OWNER.SCT_AUDIT TO BFGREST_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY to BFGREST_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_AUDIT_ID_SEQ TO BFGREST_APPUSER_ROLE;

GRANT SELECT ON SI_OWNER.SI_VERSION to BFGREST_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.WORKFLOW_CONTEXT to BFGREST_APPUSER_ROLE;

CREATE USER BFGREST_APPUSER IDENTIFIED BY Bfgrest_12345_dev
Profile EF_ORACLE_BATCH_NOEXPIRE
Default tablespace users temporary tablespace user_temp;

GRANT CREATE SESSION TO BFGREST_APPUSER_ROLE;

GRANT BFGREST_APPUSER_ROLE TO BFGREST_APPUSER;

GRANT CREATE SYNONYM TO BFGREST_APPUSER_ROLE;

Alter session set current_Schema=BFGREST_APPUSER;

SET ROLE BFGREST_APPUSER_ROLE;

create or replace synonym "SCT_AUDIT" for "RBS_BFG_CUSTOM_OWNER"."SCT_AUDIT";
create or replace synonym "SCT_BUNDLE" for "RBS_BFG_CUSTOM_OWNER"."SCT_BUNDLE";
create or replace synonym "SCT_PAYMENT" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT";
create or replace synonym "SCT_PAYMENT_ARCHIVE" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT_ARCHIVE";
create or replace synonym "SCT_ENTITY" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY";
create or replace synonym "SCT_AUDIT_ID_SEQ" for "RBS_BFG_CUSTOM_OWNER"."SCT_AUDIT_ID_SEQ";
create or replace synonym "SI_VERSION" for "SI_OWNER"."SI_VERSION";
create or replace synonym "WORKFLOW_CONTEXT" for "SI_OWNER"."WORKFLOW_CONTEXT";

connect / as sysdba
alter session set container=DOGB1575;

CREATE ROLE BFGBP_APPUSER_ROLE NOT IDENTIFIED;

GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_ENTITY TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON RBS_BFG_CUSTOM_OWNER.SCT_TRUSTED_CERTIFICATE_LOG TO BFGBP_APPUSER_ROLE;
GRANT SELECT, UPDATE ON RBS_BFG_CUSTOM_OWNER.SCT_SCHEDULE TO BFGBP_APPUSER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT TO BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_PAYMENT_ARCHIVE TO BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.SCT_BUNDLE TO BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.SI_VERSION to BFGBP_APPUSER_ROLE;

GRANT SELECT ON SI_OWNER.FG_DELIVERY to BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.FG_ROUTE to BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.FG_ARRIVEDFILE to BFGBP_APPUSER_ROLE;
GRANT SELECT ON SI_OWNER.MBX_MESSAGE to BFGBP_APPUSER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_ASYNC_CD to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_CHANGE_CONTROL to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_DEFER_DELIVERY to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_DOC_STORAGE to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_FILE to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_FCM_MSGID_TRACKER to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_FLOW_CONTROL to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_INTERFACE to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_SWR_FILESTATUS to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_GR_TRACKING to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_MQ_TRANSFER to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_SFGLEGACY_LINK to BFGBP_APPUSER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RBS_BFG_CUSTOM_OWNER.FB_WF_THREAD to BFGBP_APPUSER_ROLE;


CREATE USER BFGBP_APPUSER IDENTIFIED BY Bfgbp_12345_dev
Profile EF_ORACLE_BATCH_NOEXPIRE
Default tablespace users temporary tablespace user_temp;

GRANT CREATE SESSION TO BFGBP_APPUSER_ROLE;

GRANT BFGBP_APPUSER_ROLE TO BFGBP_APPUSER;

GRANT CREATE SYNONYM TO BFGBP_APPUSER_ROLE;

Alter session set current_Schema=BFGBP_APPUSER;

SET ROLE BFGBP_APPUSER_ROLE;

create or replace synonym "FB_CHANGE_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."FB_CHANGE_CONTROL";
create or replace synonym "FB_ASYNC_CD" for "RBS_BFG_CUSTOM_OWNER"."FB_ASYNC_CD";
create or replace synonym "FB_FILE" for "RBS_BFG_CUSTOM_OWNER"."FB_FILE";
create or replace synonym "FB_DOC_STORAGE" for "RBS_BFG_CUSTOM_OWNER"."FB_DOC_STORAGE";
create or replace synonym "FB_DEFER_DELIVERY" for "RBS_BFG_CUSTOM_OWNER"."FB_DEFER_DELIVERY";
create or replace synonym "FB_GR_FCM_MSGID_TRACKER" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_FCM_MSGID_TRACKER";
create or replace synonym "FB_GR_FLOW_CONTROL" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_FLOW_CONTROL";
create or replace synonym "FB_GR_INTERFACE" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_INTERFACE";
create or replace synonym "FB_GR_SWR_FILESTATUS" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_SWR_FILESTATUS";
create or replace synonym "FB_GR_TRACKING" for "RBS_BFG_CUSTOM_OWNER"."FB_GR_TRACKING";
create or replace synonym "FB_MQ_TRANSFER" for "RBS_BFG_CUSTOM_OWNER"."FB_MQ_TRANSFER";
create or replace synonym "FB_SFGLEGACY_LINK" for "RBS_BFG_CUSTOM_OWNER"."FB_SFGLEGACY_LINK";
create or replace synonym "FB_WF_THREAD" for "RBS_BFG_CUSTOM_OWNER"."FB_WF_THREAD";
create or replace synonym "SCT_ENTITY" for "RBS_BFG_CUSTOM_OWNER"."SCT_ENTITY";
create or replace synonym "SCT_TRUSTED_CERTIFICATE" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE";
create or replace synonym "SCT_TRUSTED_CERTIFICATE_LOG" for "RBS_BFG_CUSTOM_OWNER"."SCT_TRUSTED_CERTIFICATE_LOG";
create or replace synonym "SCT_SCHEDULE" for "RBS_BFG_CUSTOM_OWNER"."SCT_SCHEDULE";
create or replace synonym "SCT_PAYMENT" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT";
create or replace synonym "SCT_PAYMENT_ARCHIVE" for "RBS_BFG_CUSTOM_OWNER"."SCT_PAYMENT_ARCHIVE";
create or replace synonym "SCT_BUNDLE" for "RBS_BFG_CUSTOM_OWNER"."SCT_BUNDLE";
create or replace synonym "SI_VERSION" for "SI_OWNER"."SI_VERSION";
create or replace synonym "FG_DELIVERY" for "SI_OWNER"."FG_DELIVERY";
create or replace synonym "FG_ROUTE" for "SI_OWNER"."FG_ROUTE";
create or replace synonym "FG_ARRIVEDFILE" for "SI_OWNER"."FG_ARRIVEDFILE";
create or replace synonym "MBX_MESSAGE" for "SI_OWNER"."MBX_MESSAGE";

Alter session set current_Schema=RBS_BFG_CUSTOM_OWNER;
create or replace public synonym "FB_FILE" for "RBS_BFG_CUSTOM_OWNER"."FB_FILE";
create or replace public synonym "FB_DOC_STORAGE" for "RBS_BFG_CUSTOM_OWNER"."FB_DOC_STORAGE";
GRANT SELECT,UPDATE ON "RBS_BFG_CUSTOM_OWNER"."FB_FILE" to SI_OWNER;
GRANT SELECT ON "RBS_BFG_CUSTOM_OWNER"."FB_DOC_STORAGE" to SI_OWNER;


