export const ENTITY_DISPLAY_NAMES = {
    service: 'Entity type',
    entity: 'Entity',
    routeInbound: 'Route Inbound',
    inboundRequestorDN: 'Inbound Requestor DN',
    inboundResponderDN: 'Inbound Responder DN',
    inboundService: 'Inbound Service',
    inboundRequestType: 'Inbound Request Type',
    inboundDir: 'Inbound Directory',
    inboundRoutingRule: 'Inbound Routing Rule',
    requestorDN: 'Requestor DN',
    responderDN: 'Responder DN',
    requestType: 'Request Type',
    trace: 'Trace',
    snF: 'SnF',
    deliveryNotification: 'Delivery Notification',
    nonRepudiation: 'Non-Repudiation',
    e2eSigning: 'End to End Signing',
    deliveryNotifDN: 'Delivery Notification DN',
    deliveryNotifRT: 'Delivery Notification RT',
    requestRef: 'Request Reference',
    fileInfo: 'File Info',
    fileDesc: 'File Description',
    transferInfo: 'Transfer Info',
    transferDesc: 'Transfer Description',
    changerComments: 'Changer comments'
};
