export const ENTITY_SERVICE_TYPE = {
    GPL: 'GPL',
    SCT: 'SCT',
};

export const ENTITY_TRANSMIT_FILE_TYPE = {
    ICF: 'ICF',
    IQF: 'IQF',
};

export const ENTITY_PERMISSIONS = {
    CREATE_SCT: 'SFG_UI_SCT_CREATE_ENTITY_SCT',
    CREATE_GPL: 'SFG_UI_SCT_CREATE_ENTITY_GPL',
    EDIT_SCT: 'SFG_UI_SCT_EDIT_ENTITY_SCT',
    EDIT_GPL: 'SFG_UI_SCT_EDIT_ENTITY_GPL',
    VIEW: 'SFG_UI_SCT_ENTITY'
};
